// This file was generated by Mendix Modeler 7.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package pushnotifications.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the PushNotifications module

	/**
	* In Milliseconds
	*/
	public static java.lang.Long getDeliveyRetryBaseInterval()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("PushNotifications.DeliveyRetryBaseInterval");
	}

	public static java.lang.String getGCMSendUrl()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("PushNotifications.GCMSendUrl");
	}

	public static java.lang.String getLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("PushNotifications.LogNode");
	}

	public static java.lang.Long getMaxFailedCount()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("PushNotifications.MaxFailedCount");
	}

	/**
	* Number of characters of the registration ids to write in log messages.
	*/
	public static java.lang.Long getRegistrationIdCutoff()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("PushNotifications.RegistrationIdCutoff");
	}
}