// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tinysqlstudio.proxies;

public class SearchObjectDoc extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TinySqlStudio.SearchObjectDoc";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SearchObjectDoc(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TinySqlStudio.SearchObjectDoc"));
	}

	protected SearchObjectDoc(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject searchObjectDocMendixObject)
	{
		super(context, searchObjectDocMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("TinySqlStudio.SearchObjectDoc", searchObjectDocMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TinySqlStudio.SearchObjectDoc");
	}

	/**
	 * @deprecated Use 'SearchObjectDoc.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static tinysqlstudio.proxies.SearchObjectDoc initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return tinysqlstudio.proxies.SearchObjectDoc.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static tinysqlstudio.proxies.SearchObjectDoc initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new tinysqlstudio.proxies.SearchObjectDoc(context, mendixObject);
	}

	public static tinysqlstudio.proxies.SearchObjectDoc load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return tinysqlstudio.proxies.SearchObjectDoc.initialize(context, mendixObject);
	}

	public static java.util.List<tinysqlstudio.proxies.SearchObjectDoc> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<tinysqlstudio.proxies.SearchObjectDoc> result = new java.util.ArrayList<tinysqlstudio.proxies.SearchObjectDoc>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TinySqlStudio.SearchObjectDoc" + xpathConstraint))
			result.add(tinysqlstudio.proxies.SearchObjectDoc.initialize(context, obj));
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final tinysqlstudio.proxies.SearchObjectDoc that = (tinysqlstudio.proxies.SearchObjectDoc) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TinySqlStudio.SearchObjectDoc";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
