// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tinysqlstudio.proxies;

public class SearchObject
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject searchObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TinySqlStudio.SearchObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Sql("Sql"),
		Header("Header"),
		Data("Data"),
		PageNo("PageNo"),
		TotalCount("TotalCount"),
		PagingSql("PagingSql"),
		DisplayCount("DisplayCount");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SearchObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TinySqlStudio.SearchObject"));
	}

	protected SearchObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject searchObjectMendixObject)
	{
		if (searchObjectMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TinySqlStudio.SearchObject", searchObjectMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TinySqlStudio.SearchObject");

		this.searchObjectMendixObject = searchObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SearchObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static tinysqlstudio.proxies.SearchObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return tinysqlstudio.proxies.SearchObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static tinysqlstudio.proxies.SearchObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new tinysqlstudio.proxies.SearchObject(context, mendixObject);
	}

	public static tinysqlstudio.proxies.SearchObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return tinysqlstudio.proxies.SearchObject.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Sql
	 */
	public final java.lang.String getSql()
	{
		return getSql(getContext());
	}

	/**
	 * @param context
	 * @return value of Sql
	 */
	public final java.lang.String getSql(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sql.toString());
	}

	/**
	 * Set value of Sql
	 * @param sql
	 */
	public final void setSql(java.lang.String sql)
	{
		setSql(getContext(), sql);
	}

	/**
	 * Set value of Sql
	 * @param context
	 * @param sql
	 */
	public final void setSql(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sql)
	{
		getMendixObject().setValue(context, MemberNames.Sql.toString(), sql);
	}

	/**
	 * @return value of Header
	 */
	public final java.lang.String getHeader()
	{
		return getHeader(getContext());
	}

	/**
	 * @param context
	 * @return value of Header
	 */
	public final java.lang.String getHeader(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Header.toString());
	}

	/**
	 * Set value of Header
	 * @param header
	 */
	public final void setHeader(java.lang.String header)
	{
		setHeader(getContext(), header);
	}

	/**
	 * Set value of Header
	 * @param context
	 * @param header
	 */
	public final void setHeader(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String header)
	{
		getMendixObject().setValue(context, MemberNames.Header.toString(), header);
	}

	/**
	 * @return value of Data
	 */
	public final java.lang.String getData()
	{
		return getData(getContext());
	}

	/**
	 * @param context
	 * @return value of Data
	 */
	public final java.lang.String getData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Data.toString());
	}

	/**
	 * Set value of Data
	 * @param data
	 */
	public final void setData(java.lang.String data)
	{
		setData(getContext(), data);
	}

	/**
	 * Set value of Data
	 * @param context
	 * @param data
	 */
	public final void setData(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String data)
	{
		getMendixObject().setValue(context, MemberNames.Data.toString(), data);
	}

	/**
	 * @return value of PageNo
	 */
	public final java.lang.Integer getPageNo()
	{
		return getPageNo(getContext());
	}

	/**
	 * @param context
	 * @return value of PageNo
	 */
	public final java.lang.Integer getPageNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PageNo.toString());
	}

	/**
	 * Set value of PageNo
	 * @param pageno
	 */
	public final void setPageNo(java.lang.Integer pageno)
	{
		setPageNo(getContext(), pageno);
	}

	/**
	 * Set value of PageNo
	 * @param context
	 * @param pageno
	 */
	public final void setPageNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer pageno)
	{
		getMendixObject().setValue(context, MemberNames.PageNo.toString(), pageno);
	}

	/**
	 * @return value of TotalCount
	 */
	public final java.lang.Integer getTotalCount()
	{
		return getTotalCount(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalCount
	 */
	public final java.lang.Integer getTotalCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalCount.toString());
	}

	/**
	 * Set value of TotalCount
	 * @param totalcount
	 */
	public final void setTotalCount(java.lang.Integer totalcount)
	{
		setTotalCount(getContext(), totalcount);
	}

	/**
	 * Set value of TotalCount
	 * @param context
	 * @param totalcount
	 */
	public final void setTotalCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalcount)
	{
		getMendixObject().setValue(context, MemberNames.TotalCount.toString(), totalcount);
	}

	/**
	 * @return value of PagingSql
	 */
	public final java.lang.String getPagingSql()
	{
		return getPagingSql(getContext());
	}

	/**
	 * @param context
	 * @return value of PagingSql
	 */
	public final java.lang.String getPagingSql(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PagingSql.toString());
	}

	/**
	 * Set value of PagingSql
	 * @param pagingsql
	 */
	public final void setPagingSql(java.lang.String pagingsql)
	{
		setPagingSql(getContext(), pagingsql);
	}

	/**
	 * Set value of PagingSql
	 * @param context
	 * @param pagingsql
	 */
	public final void setPagingSql(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pagingsql)
	{
		getMendixObject().setValue(context, MemberNames.PagingSql.toString(), pagingsql);
	}

	/**
	 * @return value of DisplayCount
	 */
	public final java.lang.Integer getDisplayCount()
	{
		return getDisplayCount(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayCount
	 */
	public final java.lang.Integer getDisplayCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DisplayCount.toString());
	}

	/**
	 * Set value of DisplayCount
	 * @param displaycount
	 */
	public final void setDisplayCount(java.lang.Integer displaycount)
	{
		setDisplayCount(getContext(), displaycount);
	}

	/**
	 * Set value of DisplayCount
	 * @param context
	 * @param displaycount
	 */
	public final void setDisplayCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer displaycount)
	{
		getMendixObject().setValue(context, MemberNames.DisplayCount.toString(), displaycount);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return searchObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final tinysqlstudio.proxies.SearchObject that = (tinysqlstudio.proxies.SearchObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TinySqlStudio.SearchObject";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
