// This file was generated by Mendix Modeler 7.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tinysqlstudio.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the TinySqlStudio module

	/**
	* 1ページに表示する件数を指定。デフォルト値は100
	*/
	public static java.lang.Long getDisplayCount()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TinySqlStudio.DisplayCount");
	}
}