// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tinysqlstudio.actions;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class RetrieveCountAdvanced extends CustomJavaAction<java.lang.Long>
{
	private java.lang.String Sql;

	public RetrieveCountAdvanced(IContext context, java.lang.String Sql)
	{
		super(context);
		this.Sql = Sql;
	}

	@Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		logger.info("executeAction: " + this.Sql);
		return Core.dataStorage().executeWithConnection(connection -> {
			try {
				PreparedStatement stmt = connection
						.prepareStatement("select count(*) from (" + this.Sql.replaceAll(";", "") + ") as cntE");
				ResultSet rset = stmt.executeQuery();

				if (!rset.next()) {
					return 0l;
				}

				return rset.getLong(1);

			} catch (SQLException e) {
				logger.error("Failed to execute sql statement: " + e.getMessage());
				throw new MendixRuntimeException(e);
			}
		});
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "RetrieveCountAdvanced";
	}

	// BEGIN EXTRA CODE
	private final ILogNode logger = Core.getLogger(this.getClass().getName());
	// END EXTRA CODE
}
