// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package restservices.proxies;

public enum HttpMethod
{
	GET(new java.lang.String[][] { new java.lang.String[] { "en_US", "GET" }, new java.lang.String[] { "nl_NL", "GET" } }),
	POST(new java.lang.String[][] { new java.lang.String[] { "en_US", "POST" }, new java.lang.String[] { "nl_NL", "POST" } }),
	PUT(new java.lang.String[][] { new java.lang.String[] { "en_US", "PUT" }, new java.lang.String[] { "nl_NL", "PUT" } }),
	DELETE(new java.lang.String[][] { new java.lang.String[] { "en_US", "DELETE" }, new java.lang.String[] { "nl_NL", "DELETE" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private HttpMethod(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
